package env

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateEnvFile generates a .env file with strict 0600 permissions.
// If comments map is provided, comments are rendered above the corresponding variable.
func GenerateEnvFile(targetPath string, values map[string]string, comments map[string]string) error {
	dir := filepath.Dir(targetPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	var buf bytes.Buffer

	// Sort keys for deterministic output
	keys := make([]string, 0, len(values))
	for k := range values {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		if comments != nil {
			if comment, ok := comments[k]; ok && strings.TrimSpace(comment) != "" {
				lines := strings.Split(comment, "\n")
				for _, line := range lines {
					buf.WriteString(fmt.Sprintf("# %s\n", strings.TrimSpace(line)))
				}
			}
		}

		val := values[k]
		formattedVal := formatEnvValue(val)
		buf.WriteString(fmt.Sprintf("%s=%s\n", k, formattedVal))
	}

	if err := os.WriteFile(targetPath, buf.Bytes(), 0600); err != nil {
		return fmt.Errorf("failed to write env file %s: %w", targetPath, err)
	}

	// Explicitly ensure permissions are 0600 in case the file previously existed
	if err := os.Chmod(targetPath, 0600); err != nil {
		return fmt.Errorf("failed to chmod env file %s: %w", targetPath, err)
	}

	return nil
}

// GenerateFromSchema generates a .env file using schema defaults and variable descriptions as comments.
func GenerateFromSchema(targetPath string, schema *EnvSchema, overrides map[string]string) error {
	if schema == nil {
		return fmt.Errorf("schema cannot be nil")
	}

	values := make(map[string]string)
	comments := make(map[string]string)

	for _, v := range schema.Variables {
		comments[v.Name] = v.Description
		if val, ok := overrides[v.Name]; ok {
			values[v.Name] = val
		} else {
			values[v.Name] = v.Default
		}
	}

	return GenerateEnvFile(targetPath, values, comments)
}

// GenerateMCPEnv generates .cursor/mcp.env with tokens for Cursor MCP servers.
// File permissions are strictly set to 0600.
func GenerateMCPEnv(targetPath string, tokens map[string]string) error {
	dir := filepath.Dir(targetPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by manova CLI for Cursor MCP servers\n")
	buf.WriteString("# File permissions must remain 0600 for security.\n\n")

	keys := make([]string, 0, len(tokens))
	for k := range tokens {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		val := tokens[k]
		formattedVal := formatEnvValue(val)
		buf.WriteString(fmt.Sprintf("%s=%s\n", k, formattedVal))
	}

	if err := os.WriteFile(targetPath, buf.Bytes(), 0600); err != nil {
		return fmt.Errorf("failed to write MCP env file %s: %w", targetPath, err)
	}

	if err := os.Chmod(targetPath, 0600); err != nil {
		return fmt.Errorf("failed to chmod MCP env file %s: %w", targetPath, err)
	}

	return nil
}

// formatEnvValue formats a string for output in an env file, quoting when necessary.
func formatEnvValue(val string) string {
	if val == "" {
		return `""`
	}

	needsQuotes := strings.ContainsAny(val, " \t\n\"'#$`\\") || strings.HasPrefix(val, " ") || strings.HasSuffix(val, " ")
	if !needsQuotes {
		return val
	}

	// Use double quotes and escape internal quotes/newlines
	escaped := strings.ReplaceAll(val, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	escaped = strings.ReplaceAll(escaped, "\n", `\n`)
	escaped = strings.ReplaceAll(escaped, "\r", `\r`)
	escaped = strings.ReplaceAll(escaped, "\t", `\t`)
	escaped = strings.ReplaceAll(escaped, `$`, `\$`)

	return `"` + escaped + `"`
}
