.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-invite - Manage developer onboarding invite tokens


.SH SYNOPSIS
.PP
\fBorbit invite [flags]\fP


.SH DESCRIPTION
.PP
Create, list, and revoke cryptographically signed developer onboarding invitations.
Invitations are HMAC-SHA256 signed single-use or scoped tokens with built-in expiration
and claims for automated developer onboarding.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for invite


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit(1)\fP, \fBorbit-invite-create(1)\fP, \fBorbit-invite-list(1)\fP, \fBorbit-invite-revoke(1)\fP
