.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-admin-rotate-secret - Rotate root master signing secret in the sealed owner vault


.SH SYNOPSIS
.PP
\fBorbit admin rotate-secret [flags]\fP


.SH DESCRIPTION
.PP
Generates a fresh 32-byte cryptographic root signing secret and seals the vault.
WARNING: All developer onboarding invitation tokens signed with the previous secret will be invalidated.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rotate-secret

.PP
\fB--store\fP=""
	Custom path to owner storage vault file

.PP
\fB-y\fP, \fB--yes\fP[=false]
	Skip interactive confirmation prompt


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit-admin(1)\fP
