.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-config-path - Print path to the configuration file


.SH SYNOPSIS
.PP
\fBorbit config path [flags]\fP


.SH DESCRIPTION
.PP
Outputs the active filesystem path to the Orbit CLI configuration file.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for path


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to configuration file


.SH SEE ALSO
.PP
\fBorbit-config(1)\fP
