.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-version - Print the CLI version and build metadata


.SH SYNOPSIS
.PP
\fBorbit version [flags]\fP


.SH DESCRIPTION
.PP
Print the CLI version and build metadata


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit(1)\fP
