.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-env - Manage and validate workspace environment variables and .env files


.SH SYNOPSIS
.PP
\fBorbit env [flags]\fP


.SH DESCRIPTION
.PP
Validate project .env files against .env.schema.yaml contracts, generate initial .env files, and manage MCP secrets.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for env


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit(1)\fP, \fBorbit-env-check(1)\fP, \fBorbit-env-setup(1)\fP
