.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-self-update - Update the Orbit CLI binary to the latest release


.SH SYNOPSIS
.PP
\fBorbit self-update [flags]\fP


.SH DESCRIPTION
.PP
Checks GitHub releases for the latest Orbit CLI binary, displays release highlights, and performs atomic binary replacement.


.SH OPTIONS
.PP
\fB--check\fP[=false]
	Check for updates without downloading or installing

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for self-update

.PP
\fB-y\fP, \fB--yes\fP[=false]
	Automatically accept update confirmation prompt


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit(1)\fP
