.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-dev-tier2 - Start Tier 2 Orbit services (orbit-auth, orbit-notifications, orbit-api-gateway)


.SH SYNOPSIS
.PP
\fBorbit dev tier2 [flags]\fP


.SH DESCRIPTION
.PP
Start Tier 2 Orbit services (orbit-auth, orbit-notifications, orbit-api-gateway)


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for tier2


.SH SEE ALSO
.PP
\fBorbit-dev(1)\fP
