.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-migrate - Run and inspect workspace state migrations


.SH SYNOPSIS
.PP
\fBorbit migrate [flags]\fP


.SH DESCRIPTION
.PP
Executes pending workspace migrations (directory structure, git hooks, Cursor rules, MCP configs) and tracks applied state in .manova/state.json.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for migrate


.SH SEE ALSO
.PP
\fBorbit(1)\fP, \fBorbit-migrate-status(1)\fP
