.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-invite-revoke - Revoke an active developer onboarding invitation


.SH SYNOPSIS
.PP
\fBorbit invite revoke  [flags]\fP


.SH DESCRIPTION
.PP
Marks an invitation token as revoked by its token string or invite ID, preventing further claim attempts.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for revoke

.PP
\fB--store-file\fP=""
	Custom path to invites storage file


.SH SEE ALSO
.PP
\fBorbit-invite(1)\fP
