.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-completion - Generate the autocompletion script for the specified shell


.SH SYNOPSIS
.PP
\fBorbit completion [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for orbit for the specified shell.
See each sub-command's help for details on how to use the generated script.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH SEE ALSO
.PP
\fBorbit(1)\fP, \fBorbit-completion-bash(1)\fP, \fBorbit-completion-fish(1)\fP, \fBorbit-completion-powershell(1)\fP, \fBorbit-completion-zsh(1)\fP
