.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-port-allocate - Suggest a bindable dynamic port; no reservation is retained


.SH SYNOPSIS
.PP
\fBorbit port allocate   [flags]\fP


.SH DESCRIPTION
.PP
Suggest a bindable dynamic port; no reservation is retained


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for allocate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit-port(1)\fP
