.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-assets-add - Hash, upload, and gitignore a file; update orbit-assets.yaml


.SH SYNOPSIS
.PP
\fBorbit assets add  [flags]\fP


.SH DESCRIPTION
.PP
Hash, upload, and gitignore a file; update orbit-assets.yaml


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for add


.SH SEE ALSO
.PP
\fBorbit-assets(1)\fP
