.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-migrate-status - Show status of all registered workspace migrations


.SH SYNOPSIS
.PP
\fBorbit migrate status [flags]\fP


.SH DESCRIPTION
.PP
Show status of all registered workspace migrations


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for status


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit-migrate(1)\fP
