.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-completion-zsh - Generate the autocompletion script for zsh


.SH SYNOPSIS
.PP
\fBorbit completion zsh [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for zsh


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for zsh


.SH SEE ALSO
.PP
\fBorbit-completion(1)\fP
