.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-admin - Manage platform ownership verification and root cryptographic secrets


.SH SYNOPSIS
.PP
\fBorbit admin [flags]\fP


.SH DESCRIPTION
.PP
Commands to verify server and platform administrative ownership, manage
cryptographic root signing secrets, and check ownership vault status.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for admin


.SH SEE ALSO
.PP
\fBorbit(1)\fP, \fBorbit-admin-grant(1)\fP, \fBorbit-admin-init(1)\fP, \fBorbit-admin-rotate-secret(1)\fP, \fBorbit-admin-status(1)\fP, \fBorbit-admin-totp(1)\fP, \fBorbit-admin-verify(1)\fP
