.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-dev-up - Start local development stack containers


.SH SYNOPSIS
.PP
\fBorbit dev up [modules...] [flags]\fP


.SH DESCRIPTION
.PP
Start local development stack containers


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for up

.PP
\fB--timeout\fP=15s
	Timeout when waiting for service readiness

.PP
\fB-w\fP, \fB--wait\fP[=false]
	Wait for core services to become responsive


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit-dev(1)\fP
