.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-port-list - List base ports and deterministic slots for all registered projects


.SH SYNOPSIS
.PP
\fBorbit port list [flags]\fP


.SH DESCRIPTION
.PP
List base ports and deterministic slots for all registered projects


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--scan\fP[=true]
	Scan active network sockets on loopback


.SH SEE ALSO
.PP
\fBorbit-port(1)\fP
