.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-dev-logs - Stream logs from local dev stack containers


.SH SYNOPSIS
.PP
\fBorbit dev logs [service] [flags]\fP


.SH DESCRIPTION
.PP
Stream logs from local dev stack containers


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for logs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit-dev(1)\fP
