.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-dev - Control and orchestrate local development stacks and containers


.SH SYNOPSIS
.PP
\fBorbit dev [flags]\fP


.SH DESCRIPTION
.PP
Executes Docker Compose and orchestration scripts located in orbit/orbit-infra to start/stop local databases, queues, identity services, and developer portals.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for dev


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit(1)\fP, \fBorbit-dev-caddy(1)\fP, \fBorbit-dev-down(1)\fP, \fBorbit-dev-logs(1)\fP, \fBorbit-dev-portal(1)\fP, \fBorbit-dev-tier2(1)\fP, \fBorbit-dev-up(1)\fP
