.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-staff-create - Create a staff member (lldap + mailbox)


.SH SYNOPSIS
.PP
\fBorbit staff create [flags]\fP


.SH DESCRIPTION
.PP
Create a staff member and optionally generate a signed onboarding invite token with --invite.


.SH OPTIONS
.PP
\fB--forward\fP=""
	personal forward email (required)

.PP
\fB--groups\fP=""
	comma-separated groups (default server-side: dev)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--idempotency-key\fP=""
	idempotency key (generated if empty)

.PP
\fB--invite\fP[=false]
	generate and print a signed onboarding invite token after account creation

.PP
\fB--invite-email\fP=""
	email address for the invite token (defaults to --forward value)

.PP
\fB--invite-ttl\fP="7d"
	invite token TTL (e.g. 7d, 24h, 168h)

.PP
\fB--name\fP=""
	display name

.PP
\fB--totp\fP[=false]
	enroll Authelia TOTP

.PP
\fB--uid\fP=""
	staff uid (required)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--owner-store\fP=""
	path to owner.json vault

.PP
\fB--server\fP=""
	staff server URL (or ORBIT_STAFF_URL)


.SH SEE ALSO
.PP
\fBorbit-staff(1)\fP
