.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-port-allocate - Dynamically allocate the next free port in a project's 50-port range


.SH SYNOPSIS
.PP
\fBorbit port allocate   [flags]\fP


.SH DESCRIPTION
.PP
Dynamically allocate the next free port in a project's 50-port range


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for allocate


.SH SEE ALSO
.PP
\fBorbit-port(1)\fP
