.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-config-set - Set a configuration key-value pair


.SH SYNOPSIS
.PP
\fBorbit config set   [flags]\fP


.SH DESCRIPTION
.PP
Update a specific configuration setting by key and persist it to the configuration file.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to configuration file


.SH SEE ALSO
.PP
\fBorbit-config(1)\fP
