.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-assets-push - Upload index objects that are missing from R2


.SH SYNOPSIS
.PP
\fBorbit assets push [scope] [flags]\fP


.SH DESCRIPTION
.PP
Upload index objects that are missing from R2


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for push

.PP
\fB--manifest\fP=""
	Path to workspace.yaml


.SH SEE ALSO
.PP
\fBorbit-assets(1)\fP
