.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-assets - Sync gitignored media with private Cloudflare R2


.SH SYNOPSIS
.PP
\fBorbit assets [flags]\fP


.SH DESCRIPTION
.PP
Pull, push, add, and status for files listed in orbit-assets.yaml. Git stores the index; R2 stores bytes.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for assets


.SH SEE ALSO
.PP
\fBorbit(1)\fP, \fBorbit-assets-add(1)\fP, \fBorbit-assets-pull(1)\fP, \fBorbit-assets-push(1)\fP, \fBorbit-assets-status(1)\fP
