.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-env-check - Validate project .env files against their .env.schema.yaml contracts


.SH SYNOPSIS
.PP
\fBorbit env check [path] [flags]\fP


.SH DESCRIPTION
.PP
Validate project .env files against their .env.schema.yaml contracts


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for check


.SH SEE ALSO
.PP
\fBorbit-env(1)\fP
