.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit - Orbit developer platform and workspace orchestrator


.SH SYNOPSIS
.PP
\fBorbit [flags]\fP


.SH DESCRIPTION
.PP
Orbit developer onboarding, multi-repo sync, and dev stack orchestrator. (Shortcut: 'o')


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for orbit


.SH SEE ALSO
.PP
\fBorbit-admin(1)\fP, \fBorbit-assets(1)\fP, \fBorbit-completion(1)\fP, \fBorbit-config(1)\fP, \fBorbit-dev(1)\fP, \fBorbit-doc(1)\fP, \fBorbit-doctor(1)\fP, \fBorbit-env(1)\fP, \fBorbit-init(1)\fP, \fBorbit-invite(1)\fP, \fBorbit-migrate(1)\fP, \fBorbit-onboard(1)\fP, \fBorbit-port(1)\fP, \fBorbit-self-update(1)\fP, \fBorbit-staff(1)\fP, \fBorbit-status(1)\fP, \fBorbit-sync(1)\fP, \fBorbit-uninstall(1)\fP, \fBorbit-update(1)\fP, \fBorbit-version(1)\fP
