.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-port - Manage and inspect the hybrid 50-port allocation model


.SH SYNOPSIS
.PP
\fBorbit port [flags]\fP


.SH DESCRIPTION
.PP
Inspect project port ranges (50-port blocks), deterministic service slots (0-9), and dynamically allocate ports (10-49).


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for port


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit(1)\fP, \fBorbit-port-allocate(1)\fP, \fBorbit-port-list(1)\fP
