.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-dev-caddy - Manage local Caddy reverse proxy


.SH SYNOPSIS
.PP
\fBorbit dev caddy [reload|restart|logs] [flags]\fP


.SH DESCRIPTION
.PP
Manage local Caddy reverse proxy


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for caddy


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit-dev(1)\fP
