.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-assets-status - Show missing or mismatched local assets


.SH SYNOPSIS
.PP
\fBorbit assets status [scope] [flags]\fP


.SH DESCRIPTION
.PP
Show missing or mismatched local assets


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for status

.PP
\fB--manifest\fP=""
	Path to workspace.yaml


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	Custom path to Orbit CLI configuration file


.SH SEE ALSO
.PP
\fBorbit-assets(1)\fP
