.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-completion - Generate zsh autocompletion


.SH SYNOPSIS
.PP
\fBorbit completion [flags]\fP


.SH DESCRIPTION
.PP
Generate zsh autocompletion


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH SEE ALSO
.PP
\fBorbit(1)\fP, \fBorbit-completion-zsh(1)\fP
