.nh
.TH "ORBIT" "1" "Aug 2026" "Orbit Developer Platform" "Orbit Platform Manual"

.SH NAME
.PP
orbit-dev-portal - Open or print the local developer portal URL


.SH SYNOPSIS
.PP
\fBorbit dev portal [flags]\fP


.SH DESCRIPTION
.PP
Open or print the local developer portal URL


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for portal


.SH SEE ALSO
.PP
\fBorbit-dev(1)\fP
